### PR TITLE
new navbar

### LINKED ISSUE #53: New navbar
The issue opened to remove unnecessary/duplicated logon/logoff buttons in navbar.
This is not something fundamental but will clean a bit our front end styling part.

### PR DESCRIPTION
**Pull request by inlibra-cpa**
Link to issue on project board (https://github.com/jimenezmiguela/Help_Find/issues/53) -->

 improved navbar. removed excessive login/logoff buttons. Main purpose: create user friendly interface. 
[image](https://user-images.githubusercontent.com/54969014/166090305-3600ce5d-643e-4f69-a897-d930a378654f.png) 

## Type of Change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] Maintenance or Refactor (non-breaking change which does not affect existing functionality)

## Checklist

- [x ] I tested my changes locally
- [ ] I added tests to cover new functionality
- [ ] All new and existing tests are passing (`bundle exec rspec`)
- [ ] I updated my branch with master so that they can be merged easily

### CODE REVIEW

**Review by olegkolyaka78 — COMMENTED** [review]
Please add screenshots of new navbar view

**Comment by inlibra-cpa** [comment]
There is a screenshot attached Oleg.

**Review by olegkolyaka78 — APPROVED** [review]

**Comment by inlibra-cpa** [comment]
Thanks Oleg!

**Comment by olegkolyaka78** [comment]
Let's merge. If any changes needed a new task will be created with a new pull request.

**Comment by inlibra-cpa** [comment]
Absolutely.

**Pull request merged**
