### PR TITLE
Fix.  Data loading to database broken code.  Fbi menu broken code.  Incomplete code.

### LINKED ISSUE #33: Refactor:  1.  FBI API data transfer to database, with  2.  Changed search field to drop down list
1.  FBI API data transfer to database
2.  Redundancies
3.  Improve interface

### PR DESCRIPTION
**Pull request by jimenezmiguela**
Modify fbi menu code feature to work with data to database feature.  Simplify interface.

Issue Link: [ Fix Broken code: 1. FBI API data transfer to database, with 2. Changed search field to drop down list #33 ](https://github.com/jimenezmiguela/Help_Find/issues/33)

## Description

FBI API data transfer to database.
Redundancies.
Simplify interface.

Fix, unbreak fbi data to database feature (broken by menu merge).  Modify fbi menu code feature to work with data to database feature.  Simplify interface.

Before (data loading broken code, redundancies, conflicting code):
image
Tag "id" conflicting (breaking code):
image
Created new set up for Fbi menu feature (it was hijacking an id):
image
image
Created its own "id":
image
Sort misalignment (title to race sort):
image
Correct alignment (title to race sort)
image

## Type of Change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Maintenance or Refactor (non-breaking change which does not affect existing functionality)

## Checklist

- [x] I tested my changes locally
- [ ] I added tests to cover new functionality
- [x] All new and existing tests are passing (`bundle exec rspec`)
- [x] I updated my branch with master so that they can be merged easily

### CODE REVIEW

**Review by olegkolyaka78 — COMMENTED** [review]
Functionality of fbiMenu variable and its using is not evident. Is it possible to show feature in action during the next meeting?

**Comment by jimenezmiguela** [comment]
Yes of course.  Menu Div needs its own javascript variable.  fbiMenu variable is that variable.

**Review by olegkolyaka78 — APPROVED** [review]
Functionality is working, approved.

**Review by inlibra-cpa — APPROVED** [review]
This one looks good to me.

**Pull request merged**
